version: "3.2"
services:
  view_service:
    image: streamlit_api
    container_name: streamlit_view
    build:
      context: .
      dockerfile: view_service/Dockerfile
    restart: always
    ports:
      - "80:8501"
    depends_on:
      - redis
      - model_service

  redis:
    image: redis:6.2.6

  model_service:
    image: ml_service
    container_name: model_service
    build:
      context: .
      dockerfile: model_service/Dockerfile
    restart: always
    depends_on:
      - redis
